- name: Single Pipeline Setup
  ansible.builtin.include_tasks:
    file: sp_jobs.yml
  loop: "{{sp_jobs}}"

- name: Multi Pipeline Setup
  ansible.builtin.include_tasks:
    file: mp_jobs.yml
  loop: "{{mp_jobs}}"